// Package gin provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package gin

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CategoryName.
const (
	Food   CategoryName = "food"
	Music  CategoryName = "music"
	Sports CategoryName = "sports"
)

// Valid indicates whether the value is a known member of the CategoryName enum.
func (e CategoryName) Valid() bool {
	switch e {
	case Food:
		return true
	case Music:
		return true
	case Sports:
		return true
	default:
		return false
	}
}

// AlbumCreateRequest defines model for AlbumCreateRequest.
type AlbumCreateRequest struct {
	Category    Category    `json:"category"`
	ReleaseDate ReleaseDate `json:"releaseDate"`
	Title       string      `json:"title"`
}

// AlbumUpdateRequest defines model for AlbumUpdateRequest.
type AlbumUpdateRequest struct {
	Category *Category `json:"category,omitempty"`
	Title    *string   `json:"title,omitempty"`
}

// Category defines model for Category.
type Category struct {
	Id   *int         `json:"id,omitempty"`
	Name CategoryName `json:"name"`
}

// CategoryName defines model for Category.Name.
type CategoryName string

// ReleaseDate defines model for ReleaseDate.
type ReleaseDate = openapi_types.Date

// AlbumResponse defines model for AlbumResponse.
type AlbumResponse struct {
	Anniversary int         `json:"anniversary"`
	Category    Category    `json:"category"`
	Id          int         `json:"id"`
	ReleaseDate ReleaseDate `json:"releaseDate"`
	Title       string      `json:"title"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// AlbumCreateRequestBody defines model for AlbumCreateRequestBody.
type AlbumCreateRequestBody = AlbumCreateRequest

// AlbumUpdateRequestBody defines model for AlbumUpdateRequestBody.
type AlbumUpdateRequestBody = AlbumUpdateRequest

// CreateAlbumJSONRequestBody defines body for CreateAlbum for application/json ContentType.
type CreateAlbumJSONRequestBody = AlbumCreateRequest

// UpdateAlbumByIdJSONRequestBody defines body for UpdateAlbumById for application/json ContentType.
type UpdateAlbumByIdJSONRequestBody = AlbumUpdateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CreateAlbum Create a new album
	// (POST /albums)
	CreateAlbum(c *gin.Context)
	// DeleteAlbumById Delete a album by ID
	// (DELETE /albums/{id})
	DeleteAlbumById(c *gin.Context, id int)
	// GetAlbumById Find album by ID
	// (GET /albums/{id})
	GetAlbumById(c *gin.Context, id int)
	// UpdateAlbumById Update a album by ID
	// (PATCH /albums/{id})
	UpdateAlbumById(c *gin.Context, id int)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CreateAlbum operation middleware
func (siw *ServerInterfaceWrapper) CreateAlbum(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAlbum(c)
}

// DeleteAlbumById operation middleware
func (siw *ServerInterfaceWrapper) DeleteAlbumById(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteAlbumById(c, id)
}

// GetAlbumById operation middleware
func (siw *ServerInterfaceWrapper) GetAlbumById(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAlbumById(c, id)
}

// UpdateAlbumById operation middleware
func (siw *ServerInterfaceWrapper) UpdateAlbumById(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateAlbumById(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/albums", wrapper.CreateAlbum)
	router.DELETE(options.BaseURL+"/albums/:id", wrapper.DeleteAlbumById)
	router.GET(options.BaseURL+"/albums/:id", wrapper.GetAlbumById)
	router.PATCH(options.BaseURL+"/albums/:id", wrapper.UpdateAlbumById)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1JbfT9swEMf/lei2R6tJAWkob1A21JdpqranqQ8mubZG8Q9sh6mq/L9PtpORkLRlDCpNvET2+Xt3n/tR",
	"dlBIrqRAYQ3kO9D4UKOx17JkGA6uqruazzRSi4s/d1t/U0hhUVj/SZWqWEEtkyK9N1L4M1NskFP/9VHj",
	"CnL4kD65SuOtSYfy4JxzJPr9ocr39NuTD34dAY1GSWE62S+ak79yrrRUqG1DkQrBHlEbqkMKdqsQcmDC",
	"4ho1OAIFtbiW8fZQ3LPWzhFg5biWxgqpwRtq8ZjcomPqCFhmK+yIGquZWEPE8lAzjSXkP73j1rYTOell",
	"2Q9jSVpJeXePRYBNoERTaKY8QciBetZJi9+H81lrqd+APkdj6PoFibWGLwkXfXBBoYE5Pi3DaF5T6ncv",
	"6Ug1D9dvbELfJtcDEQ9imHX0+573DYegPIijqLlPfCWl72ZeG1YAAaOktqaT7x5eQWaMyqJfqZXUnFrI",
	"wWOCoaofY7GSIdaYN9zK5OrbPPmOXFXxkZ+p2HTTSTbJvBupUFDFIIfzSTY5BwKK2k3IPA2DFD6VjEXx",
	"YMKozEvIIfZnKB+QzsbfW6Xej0K65xfh+eo8y6b79Rq7tL9fHYGLLDv+qr8XwgjWnIfd2iSX0ETgr4Q2",
	"OVq6Nr5qDZmlf9JgSnesdN5liRXGmvVp3YTzEOj1dl4G0ppytKi95g6YL4ynD213xQX51C5W10g62+l5",
	"V7rlgN1FDKm7cL7KZNbsv1eC8q8u/g1vpJHQiDa52ybzmzHABNY40nq3aE9NMjtRF74B3C9MlMfBKmqL",
	"zRBt3MQnoPuadTH8R879z4WK6RyfgvAK9WNbglpXkMPGWpWnaTYJf/lldpmlVLH0cQqOPDOqZEGrjTT2",
	"sNn07FNQm/bNlu53AAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
